---
- name: httpd
  yum:
    name: httpd
    state: latest
    update_cache: yes

- name: httpd index
  copy:
    content: "pajadura23"
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: '0644'
  register: httpd

- name: starthttpd
  service:
    name: httpd
    state: started
  when: httpd.changed

- name: firewall
  service:
    name: firewalld
    state: stopped

- name: mariaDB
  yum:
    name: mariadb-server
    state: latest
    update_cache: yes

- name: mysql index
  copy:
    content: "pajadura123"
    dest: /var/www/html/index1.html
    owner: root
    group: root
    mode: '0644'
  register: mysql

- name: start mariadb
  service:
    name: mariadb
    state: started
  when: mysql.changed

- name: install php
  yum:
    name:
      - php
      - php-mysqlnd
    state: latest
    update_cache: yes

- name: phpindex
  copy:
    content: "pajaduraw"
    dest: /var/www/html/index2.html
    owner: root
    group: root
    mode: '0644'
  register: php

- name: restart httpd
  service:
    name: httpd
    state: restarted
  when: php.changed











# tasks file for roles/pajlamp2
