---
- name: Core packages Install
  apt:
    name:
      - build-essential
      - apache2
      - php
      - openssl
      - perl
      - make
      - php-gd
      - libgd-dev
      - libapache2-mod-php
      - libperl-dev
      - libssl-dev
      - daemon
      - wget
      - apache2-utils
      - unzip
    state: latest
    update_cache: yes

- name: add nagios group
  group:
    name: nagios
    state: present

- name: add nagcmd group
  group:
    name: nagcmd
    state: present


- name: Create user
  user:
    name: nagios
    shell: /bin/bash
    comment: nagios user
    group: nagios
    password: $6$bO6H5d9/p$KoooL1i0dL.RJ3EwZSS45kzoeIW30rCT0jj7YzoB4Brn2aQ2cuaJVj3Krmd939P/uvgTHZRjy0XHFbA0L67tM0

- name: add user
  user:
    name : nagios
    group: nagcmd
    append: yes

- name: adding www-data nag
  user:
    name: www-data
    group: nagcmd
    append: yes

- name: creating dir 
  file:
    path: /downloads
    state: directory
    owner: nobody
    group: nogroup

- name: Nagios Download Link
  get_url:
    url: http://prdownloads.sourceforge.net/sourceforge/nagios/nagios-4.2.1.tar.gz
    dest: /downloads

- name: Nagios Plugins link
  get_url:
    url: https://nagios-plugins.org/download/nagios-plugins-2.3.3.tar.gz
    dest: /downloads
# tasks file for roles/pajinstall
