---
- name: Docker
  yum:
    name: docker
    state: latest
    update_cache: yes


- name: pull elasticsearch image
  containers.podman.podman_image:
    name: docker.elastic.co/elasticsearch/elasticsearch:7.10.1

- name: docker network
  containers.podman.podman_network:
    name: elastic
  become: true

- name: elasticsearch container
  containers.podman.podman_containers:
    containers:
      - name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
        state: present
        ports:
          - "9400:9400"
        networks:
          - name: elastic

- name: pull image logstash
  containers.podman.podman_image:
    name: docker.elastic.co/logstash/logstash:7.10.1

- name: logstash container
  containers.podman.podman_containers:
    containers:
      - name: logstash
        image: docker.elastic.co/logstash/logstash:7.10.1
        state: present
        port:
          - "5044:5044"
        networks:
          - name: elastic

- name: Pull kibanaimage
  containers.podman.podman_image:
    name: docker.elastic.co/kibana/kibana:7.10.1

- name: kibana container
  containers.podman.podman_containers:
    containers:
      - name: kibana
        image: docker.elastic.co/kibana/kibana:7.10.1
        state: present
        ports:
          - "5601:5601"
        networks:
          name: elastic



# tasks file for roles/pajcentos
