---
- name: Install FTP
  yum:
    name: vsftpd
    state: latest
    update_cache: yes

- name: Start FTP
  service:
    name: vsftpd
    state: started
    enabled: yes

- name: Create FTP
  user:
    name: '{{ user }}'
    password: '{{ ftp_pass }}'

- name: Deny User
  lineinfile:
    path: /etc/ssh/sshd_config
    line: "DenyUsers '{{ user }}'"
  register: successfully_denied

- name: Restart SSHD
  service:
    name: sshd
    state: restarted
  when: successfully_denied.changed

- name: Copy default Config
  copy:
    src: /etc/vsftpd/vsftpd.conf
    dest: /etc/vsftpd/vsftpd.conf.default
    remote_src: True

- name: Limit FTP users
  replace:
    path: /etc/vsftpd/vsftpd.conf
    regexp: '#chroot_local_user=YES'
    replace: 'chroot_local_user=YES'

- name: Config ftp file
  lineinfile:
    path: /etc/vsftpd/vsftpd.conf
    line: '{{ ftp_config }}'

- name: Restart vsftpd
  service:
    name: vsftpd
    state: restarted

# tasks file for roles/ftpcentos
